apiVersion: v1
kind: Pod
metadata:
  name: pod-node-affinity-required
  labels:
    name: myapp
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - {key: env, operator: Exists}
  containers:
  - name: web
    image: nginx:1.16-alpine
    ports:
      - containerPort: 80
  terminationGracePeriodSeconds: 0
