apiVersion: v1
kind: Pod
metadata:
  name: pod-node-affinity-preferred
  labels:
    name: myapp
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - {key: storage, operator: Exists}
  containers:
  - name: web
    image: nginx:1.16-alpine
    ports:
      - containerPort: 80
  terminationGracePeriodSeconds: 0
